### PR TITLE
Fixed error.

### PR DESCRIPTION
**Pull request by LawrenceHan**
Related to #13

### CODE REVIEW

**Comment by edekhayser** [comment]
As mentioned in #13, this project is in Swift 2.0, and this pull request only moves it back to 1.2

**Comment by LawrenceHan** [comment]
Oh, that was embarrassed -_______-

**Comment by LawrenceHan** [comment]
Oh, that was embarrassed -_______-

**Comment by LawrenceHan** [comment]
Oh, that was embarrassed -_______-

**Comment by LawrenceHan** [comment]
Oh, that was embarrassed -_______-

**Pull request closed without merging**
